server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
logging:
  pattern:
    console: "${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}:%line)-%msg%n}"
  level:
    org.springframework.security: ${SPRING_SECURITY_LOG_LEVEL:TRACE}
oauth:
  google:
    client_id: 642766501010-d4nsa0g0f342mdr1fojo4qb3p270j5lf.apps.googleusercontent.com
    client_secret: GOCSPX-15D93D0NeQz9RkDJDPoXhB2Bide
    redirect-uri: http://localhost:5173/oauth/kakao/redirect
  kakao:
    client-id: 63417d3ba4e2f7342d218e5e8ed30716
    redirect-uri: http://localhost:5173/oauth/kakao/redirect
spring:
  datasource:
    hikari:
      jdbc-url: jdbc:oracle:thin:@127.0.0.1:1521/orcl11
      username: scott
      password: tiger
      driver-class-name: oracle.jdbc.OracleDriver
      connection-timeout: 20000
      validation-timeout: 3000
      minimum-idle: 5
      maximum-pool-size: 12
      idle-timeout: 300000
      max-lifetime: 1200000
      auto-commit: true
      pool-name: oraPool
# 32글자 이상 문자열을 https://base64encode.org/에 넣고 클릭 시 아래의 결과 출력 ▼
# c3ByaW5nYm9vdGF1dGhhY2Nlc3N0b2tlbmhlbGxvc3ByaW5nYm9vdGF1dGhhY2Nlc3N0b2tlbmhlbGxv
# JWT서명: JWT은 토큰의 무결성 보장을 위해 서명을 사용함
# 이 때 서버는 비밀키를 이용하여 토큰에 서명하고 클라이언트가 전달한 토큰의 서명이 올바른지 검증한다.

jwt:
  secret: c3ByaW5nYm9vdGF1dGhhY2Nlc3N0b2tlbmhlbGxvc3ByaW5nYm9vdGF1dGhhY2Nlc3N0b2tlbmhlbGxv
  expiration: 3000
